Fix the curl.test.ext spawn_curl_commands ts parameter (#12358)
This fixes:

```
  File "/home/jenkins/trafficserver/tests/gold_tests_filtered/autest-site/curl.test.ext", line 33
    def spawn_curl_commands(self, cmdstr, count, retcode=0, use_default=True, ts):
                                                                              ^^
SyntaxError: parameter without a default follows parameter with a default
```

Co-authored-by: bneradt <bneradt@yahooinc.com>
(cherry picked from commit 8689842cfe06a9f4e7ec7c4107f5039d71b64e64)